spring.application.name=microservicio-auth
server.port=8080

# Actuator: expone el endpoint /actuator/health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
